services:
  - type: web
    name: ai-lawyer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python-3.10
    branch: main
    autoDeploy: true
